# Generated by Django 5.0.6 on 2024-06-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, verbose_name='Product name')),
                ('photo', models.CharField(max_length=200, null=True, verbose_name='Photo file_id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('description', models.TextField(max_length=3000, null=True, verbose_name='About Product')),
                ('category_code', models.CharField(max_length=20, verbose_name='Category code')),
                ('category_name', models.CharField(max_length=30, verbose_name='Category name')),
                ('subcategory_code', models.CharField(max_length=20, verbose_name='Ost-category-code')),
                ('subcategory_name', models.CharField(max_length=30, verbose_name='Ost-category-name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full Name')),
                ('username', models.CharField(max_length=20, null=True, unique=True, verbose_name='Username')),
                ('telegram_id', models.PositiveIntegerField(max_length=20, unique=True, verbose_name='Telegram ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
